plugins:
  eslint:
    enabled: true
exclude_patterns:
  - "src/registerServiceWorker.js"
  - "src/index.js"
  - "**/*.css"
  - "**/*.svg"
  - "**/*.png"
  - "**/*.html"
  - "**/*.md"
  - "docs/"
  - "**/*.yml"
  - "**/*.json"
  - "**/*.test.*"
  - "**/.*"
